-- Create rooms table
create table rooms (
  code text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null
);

-- Create schedules table with room_code foreign key
create table schedules (
  id bigint generated by default as identity primary key,
  date date not null,
  schedule jsonb not null,
  room_code text not null references rooms(code) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(date, room_code)
); 